# Default initial positions for husky_fr3's ros2_control fake system

initial_positions:
  fr3_finger_joint1: 0
  fr3_joint1: 0
  fr3_joint2: 0
  fr3_joint3: 0
  fr3_joint4: -1.5708
  fr3_joint5: 0
  fr3_joint6: 1.5708
  fr3_joint7: 0.7853